export const articulos = [
  {
    nombre: "Sacapuntas",
    valor: 300,
    detalle: "Marca W",
    imagen: "/imagenes/sacapuntas.jpg",
    idElemento: 4,
    disponibilidad: true,
  },
  {
    nombre: "Cuaderno",
    valor: 1000,
    detalle: "Marca Genérica",
    imagen: "/imagenes/cuaderno.jpg",
    idElemento: 1,
    disponibilidad: true,
  },
  {
    nombre: "Lápiz",
    valor: 500,
    detalle: "Marca W",
    imagen: "/imagenes/lapiz.jpg",
    idElemento: 2,
  },
  {
    nombre: "Borrador",
    valor: 200,
    detalle: "Marca Genérica",
    imagen: "/imagenes/borrador.jpg",
    idElemento: 3,
    disponibilidad: true,
  },

  {
    nombre: "Regla",
    valor: 800,
    detalle: "Marca Genérica",
    imagen: "/imagenes/regla.jpg",
    idElemento: 5,
    disponibilidad: true,
  },
  {
    nombre: "Block",
    valor: 2000,
    detalle: "Marca W",
    imagen: "/imagenes/block.jpg",
    idElemento: 6,
    disponibilidad: false,
  },
  {
    nombre: "Colores",
    valor: 25000,
    detalle: "Marca Genérica",
    imagen: "/imagenes/colores.jpg",
    idElemento: 7,
    disponibilidad: true,
  },
  {
    nombre: "Crayolas",
    valor: 3000,
    detalle: "Marca W",
    imagen: "/imagenes/crayolas.jpg",
    idElemento: 8,
    disponibilidad: true,
  },
];
